apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.2
  creationTimestamp: null
  name: deploymentgroups.codedeploy.aws.jet.crossplane.io
spec:
  group: codedeploy.aws.jet.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - awsjet
    kind: DeploymentGroup
    listKind: DeploymentGroupList
    plural: deploymentgroups
    singular: deploymentgroup
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.annotations.crossplane\.io/external-name
      name: EXTERNAL-NAME
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DeploymentGroup is the Schema for the DeploymentGroups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DeploymentGroupSpec defines the desired state of DeploymentGroup
            properties:
              deletionPolicy:
                default: Delete
                description: DeletionPolicy specifies what will happen to the underlying
                  external when this managed resource is deleted - either "Delete"
                  or "Orphan" the external resource.
                enum:
                - Orphan
                - Delete
                type: string
              forProvider:
                properties:
                  alarmConfiguration:
                    items:
                      properties:
                        alarms:
                          items:
                            type: string
                          type: array
                        enabled:
                          type: boolean
                        ignorePollAlarmFailure:
                          type: boolean
                      type: object
                    type: array
                  appName:
                    type: string
                  autoRollbackConfiguration:
                    items:
                      properties:
                        enabled:
                          type: boolean
                        events:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  autoscalingGroups:
                    items:
                      type: string
                    type: array
                  blueGreenDeploymentConfig:
                    items:
                      properties:
                        deploymentReadyOption:
                          items:
                            properties:
                              actionOnTimeout:
                                type: string
                              waitTimeInMinutes:
                                format: int64
                                type: integer
                            type: object
                          type: array
                        greenFleetProvisioningOption:
                          items:
                            properties:
                              action:
                                type: string
                            type: object
                          type: array
                        terminateBlueInstancesOnDeploymentSuccess:
                          items:
                            properties:
                              action:
                                type: string
                              terminationWaitTimeInMinutes:
                                format: int64
                                type: integer
                            type: object
                          type: array
                      type: object
                    type: array
                  deploymentConfigName:
                    type: string
                  deploymentGroupName:
                    type: string
                  deploymentStyle:
                    items:
                      properties:
                        deploymentOption:
                          type: string
                        deploymentType:
                          type: string
                      type: object
                    type: array
                  ec2TagFilter:
                    items:
                      properties:
                        key:
                          type: string
                        type:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  ec2TagSet:
                    items:
                      properties:
                        ec2TagFilter:
                          items:
                            properties:
                              key:
                                type: string
                              type:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                      type: object
                    type: array
                  ecsService:
                    items:
                      properties:
                        clusterName:
                          type: string
                        serviceName:
                          type: string
                      required:
                      - clusterName
                      - serviceName
                      type: object
                    type: array
                  loadBalancerInfo:
                    items:
                      properties:
                        elbInfo:
                          items:
                            properties:
                              name:
                                type: string
                            type: object
                          type: array
                        targetGroupInfo:
                          items:
                            properties:
                              name:
                                type: string
                            type: object
                          type: array
                        targetGroupPairInfo:
                          items:
                            properties:
                              prodTrafficRoute:
                                items:
                                  properties:
                                    listenerArns:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - listenerArns
                                  type: object
                                type: array
                              targetGroup:
                                items:
                                  properties:
                                    name:
                                      type: string
                                  required:
                                  - name
                                  type: object
                                type: array
                              testTrafficRoute:
                                items:
                                  properties:
                                    listenerArns:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - listenerArns
                                  type: object
                                type: array
                            required:
                            - prodTrafficRoute
                            - targetGroup
                            type: object
                          type: array
                      type: object
                    type: array
                  onPremisesInstanceTagFilter:
                    items:
                      properties:
                        key:
                          type: string
                        type:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  region:
                    description: Region is the region you'd like your resource to
                      be created in.
                    type: string
                  serviceRoleArn:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  triggerConfiguration:
                    items:
                      properties:
                        triggerEvents:
                          items:
                            type: string
                          type: array
                        triggerName:
                          type: string
                        triggerTargetArn:
                          type: string
                      required:
                      - triggerEvents
                      - triggerName
                      - triggerTargetArn
                      type: object
                    type: array
                required:
                - appName
                - deploymentGroupName
                - region
                - serviceRoleArn
                type: object
              providerConfigRef:
                default:
                  name: default
                description: ProviderConfigReference specifies how the provider that
                  will be used to create, observe, update, and delete this managed
                  resource should be configured.
                properties:
                  name:
                    description: Name of the referenced object.
                    type: string
                required:
                - name
                type: object
              providerRef:
                description: 'ProviderReference specifies the provider that will be
                  used to create, observe, update, and delete this managed resource.
                  Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`'
                properties:
                  name:
                    description: Name of the referenced object.
                    type: string
                required:
                - name
                type: object
              writeConnectionSecretToRef:
                description: WriteConnectionSecretToReference specifies the namespace
                  and name of a Secret to which any connection details for this managed
                  resource should be written. Connection details frequently include
                  the endpoint, username, and password required to connect to the
                  managed resource.
                properties:
                  name:
                    description: Name of the secret.
                    type: string
                  namespace:
                    description: Namespace of the secret.
                    type: string
                required:
                - name
                - namespace
                type: object
            required:
            - forProvider
            type: object
          status:
            description: DeploymentGroupStatus defines the observed state of DeploymentGroup.
            properties:
              atProvider:
                properties:
                  arn:
                    type: string
                  computePlatform:
                    type: string
                  deploymentGroupId:
                    type: string
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition
                        transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's
                        last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition
                        type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
